apiVersion: v1
kind: Pod
metadata:
  name: dummy-log-pod
spec:
  containers:
  - name: log-generator
    image: busybox
    command: ["sh", "-c", "while true; do echo $(date) >> /logs/app.log; sleep 5; done"]
    volumeMounts:
    - name: logs-volume
      mountPath: /logs
  restartPolicy: Always
  volumes:
  - name: logs-volume
    persistentVolumeClaim:
      claimName: app-logs-pvc

